spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://${MYSQL_ENDPOINT}:${MYSQL_PORT}/${MYSQL_NAME}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: false

  flyway:
    enabled: true
    validate-on-migrate: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  security:
    user:
      name: takeit
      password: takeit

  redis:
    host: ${SPRING_REDIS_HOST:redis}
    port: ${SPRING_REDIS_PORT:6379}

  cache:
    type: redis

  kafka:
    bootstrap-servers: ${KAFKA_BROKERS}
    admin:
      fail-fast: true
      properties:
        request.timeout.ms: 10000
        default.api.timeout.ms: 10000


oauth:
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    client-secret: ${KAKAO_CLIENT_SECRET}
    redirect-uri: ${KAKAO_REDIRECT_URI}
    token-uri: https://kauth.kakao.com/oauth/token
    jwk-uri: https://kauth.kakao.com/.well-known/jwks.json
    scope: profile_nickname account_email

  google:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    redirect-uri: ${GOOGLE_REDIRECT_URI}

  naver:
    request-token-uri: ${NAVER_REQUEST_TOKEN_URI}
    client-id: ${NAVER_CLIENT_ID}
    client-secret: ${NAVER_SECRET}
    redirect-uri: ${NAVER_REDIRECT_URI}
    user-info-uri: ${NAVER_USER_INFO_URI}

fastapi:
  base-url: ${FAST_API_URL}

client:
  base-url: ${CLIENT_BASE_URL}

slack:
  webhook-url: ${WEBHOOK_URL}

openai:
  secret-key: ${OPEN_AI_KEY}