spring:
  application:
    name: takeit

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true

    h2:
      console:
        enabled: true
        path: /h2-console

  security:
    user:
      name: takeit
      password: takeit



naver:
  request-token-uri: https://nid.naver.com/oauth2.0/token
  client-id: bG5y9c7SsXkdkxq2I14X
  client-secret: M35Iv92jTu
  redirect-uri: http://localhost:8080/oauth/naver
  user-info-uri: https://openapi.naver.com/v1/nid/me


springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info

  endpoint:
    health:
      show-details: always




