spring:
  config:
    activate:
      on-profile: dev
    import: optional:file:.env.dev.properties
  datasource:
    url: jdbc:mysql://${MYSQL_ENDPOINT}:${MYSQL_PORT}/${MYSQL_NAME}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

    hikari:
      maximum-pool-size: 50       # 최대 커넥션 수 (기본값 10)
      minimum-idle: 5             # 최소 유휴 커넥션 수
      idle-timeout: 900000        # 커넥션이 유휴 상태로 유지되는 최대 시간 (밀리초)
      max-lifetime: 1800000       # 커넥션 생존 시간 (30분)
      connection-timeout: 900000   # 커넥션 풀에서 커넥션을 얻기까지 기다리는 최대 시간 (30초)
      validation-timeout: 5000    # 커넥션 유효성 검사 타임아웃

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  flyway:
    enabled: false
    baselineOnMigrate: true
    locations: classpath:db/migration

  security:
    user:
      name: takeit
      password: takeit

  cache:
    type: redis
  data:
    redis:
      host: ${SPRING_REDIS_HOST}
      port: ${SPRING_REDIS_PORT}

  kafka:
    bootstrap-servers: ${KAFKA_BROKERS}
    admin:
      fail-fast: true
      properties:
        request.timeout.ms: 10000
        default.api.timeout.ms: 10000

oauth:
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    client-secret: ${KAKAO_CLIENT_SECRET}
    redirect-uri: ${KAKAO_REDIRECT_URI}
    token-uri: https://kauth.kakao.com/oauth/token
    jwk-uri: https://kauth.kakao.com/.well-known/jwks.json
    scope: profile_nickname account_email

  google:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    redirect-uri: ${GOOGLE_REDIRECT_URI}

  naver:
    request-token-uri: ${NAVER_REQUEST_TOKEN_URI}
    client-id: ${NAVER_CLIENT_ID}
    client-secret: ${NAVER_SECRET}
    redirect-uri: ${NAVER_REDIRECT_URI}
    user-info-uri: ${NAVER_USER_INFO_URI}

fastapi:
  base-url: ${FAST_API_URL}

client:
  base-url: ${CLIENT_BASE_URL}

slack:
  webhook-url: ${WEBHOOK_URL}

openai:
  secret-key: ${OPEN_AI_KEY}

logging:
  level:
    com.zaxxer.hikari.HikariConfig: DEBUG
    com.zaxxer.hikari.HikariDataSource: DEBUG
    # 커넥션 획득/반환 및 풀 상태 확인 로그
    hikari.HikariPool: DEBUG