spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=MYSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  flyway:
    enabled: false
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration

  kafka:
    bootstrap-servers: ${KAFKA_BROKERS}
    admin:
      fail-fast: true
      properties:
        request.timeout.ms: 10000
        default.api.timeout.ms: 10000


fastapi:
  base-url: ${FAST_API_URL}

client:
  base-url: ${CLIENT_BASE_URL}

slack:
  webhook-url: ${WEBHOOK_URL}