spring:
  application:
    name: takeit
  profiles:
    active: local
  config:
    import: optional:file:.env.${spring.profiles.active}.properties

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info

  endpoint:
    health:
      show-details: always

server:
  port: 9800