spring:
  application:
    name: takeit
  profiles:
    active: local
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS}
    admin:
      fail-fast: true
      properties:
        request.timeout.ms: 10000
        default.api.timeout.ms: 10000
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info

  endpoint:
    health:
      show-details: always

server:
  port: 9800