#!/usr/bin/env bash
FILE="$1"
BRANCH="$(git symbolic-ref --short HEAD)"
if [[ "$BRANCH" =~ ([A-Z]+-[0-9]+) ]]; then
  ISSUE="${BASH_REMATCH[1]}"
  grep -q "$ISSUE" "$FILE" || sed -i.bak "1s/^/$ISSUE /" "$FILE"
fi