name: CodeStyleCheck

on:
  push:
    branches-ignore:
      - main
      - develop

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set environment variables for OAuth
        run: |
          echo "KAKAO_CLIENT_ID=${{ secrets.KAKAO_CLIENT_ID }}" >> $GITHUB_ENV
          echo "KAKAO_CLIENT_SECRET=${{ secrets.KAKAO_CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "KAKAO_REDIRECT_URI=${{ secrets.KAKAO_REDIRECT_URI }}" >> $GITHUB_ENV
          echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> $GITHUB_ENV
          echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "GOOGLE_REDIRECT_URI=${{ secrets.GOOGLE_REDIRECT_URI }}" >> $GITHUB_ENV
          echo "NAVER_REQUEST_TOKEN_URI=${{ secrets.NAVER_REQUEST_TOKEN_URI }}" >> $GITHUB_ENV
          echo "NAVER_CLIENT_ID=${{ secrets.NAVER_CLIENT_ID }}" >> $GITHUB_ENV
          echo "NAVER_SECRET=${{ secrets.NAVER_SECRET }}" >> $GITHUB_ENV
          echo "NAVER_REDIRECT_URI=${{ secrets.NAVER_REDIRECT_URI }}" >> $GITHUB_ENV
          echo "NAVER_USER_INFO_URI=${{ secrets.NAVER_USER_INFO_URI }}" >> $GITHUB_ENV
          echo "SPRING_REDIS_HOST=${{ secrets.SPRING_REDIS_HOST }}" >> $GITHUB_ENV
          echo "SPRING_REDIS_PORT=${{ secrets.SPRING_REDIS_PORT }}" >> $GITHUB_ENV
          echo "FAST_API_URL=${{ secrets.FAST_API_URL }}" >> $GITHUB_ENV
          echo "CLIENT_BASE_URL=${{ secrets.CLIENT_BASE_URL }}" >> $GITHUB_ENV
          echo "KAFKA_BROKERS=${{ secrets.KAFKA_BROKERS }}" >> $GITHUB_ENV
          echo "WEBHOOK_URL=${{ secrets.WEBHOOK_URL }}" >> $GITHUB_ENV
          echo "OPEN_AI_KEY=${{ secrets.OPEN_AI_KEY }}" >> $GITHUB_ENV
          echo "TEST_MYSQL_ENDPOINT=${{ secrets.TEST_MYSQL_ENDPOINT }}" >> $GITHUB_ENV
          echo "TEST_MYSQL_USERNAME=${{ secrets.TEST_MYSQL_USERNAME }}" >> $GITHUB_ENV
          echo "TEST_MYSQL_PASSWORD=${{ secrets.TEST_MYSQL_PASSWORD }}" >> $GITHUB_ENV
          echo "TEST_MYSQL_PORT=${{ secrets.TEST_MYSQL_PORT }}" >> $GITHUB_ENV
          echo "TEST_MYSQL_NAME=${{ secrets.TEST_MYSQL_NAME }}" >> $GITHUB_ENV

      - name: Grant execute permission for Gradle
        run: chmod +x ./gradlew

      - name: Apply Spotless Format
        run: ./gradlew spotlessApply

      - name: Commit and Push if Spotless Made Changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

          if ! git diff --quiet; then
            git add .
            git commit -m "chore: apply spotless formatting"
            git push origin HEAD:${{ github.ref_name }}
          else
            echo "No changes to commit"
          fi

      - name: Check Google Style Format
        run: ./gradlew spotlessCheck

      - name: Build & Run Tests
        run: ./gradlew test

      - name: Build Application
        run: ./gradlew clean build -x test