name: CI Pipeline

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set environment variables for OAuth
        run: |
          echo "KAKAO_CLIENT_ID=${{ secrets.KAKAO_CLIENT_ID }}" >> $GITHUB_ENV
          echo "KAKAO_CLIENT_SECRET=${{ secrets.KAKAO_CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "KAKAO_REDIRECT_URI=${{ secrets.KAKAO_REDIRECT_URI }}" >> $GITHUB_ENV
          echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> $GITHUB_ENV
          echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "GOOGLE_REDIRECT_URI=${{ secrets.GOOGLE_REDIRECT_URI }}" >> $GITHUB_ENV
          echo "NAVER_REQUEST_TOKEN_URI=${{ secrets.NAVER_REQUEST_TOKEN_URI }}" >> $GITHUB_ENV
          echo "NAVER_CLIENT_ID=${{ secrets.NAVER_CLIENT_ID }}" >> $GITHUB_ENV
          echo "NAVER_SECRET=${{ secrets.NAVER_SECRET }}" >> $GITHUB_ENV
          echo "NAVER_REDIRECT_URI=${{ secrets.NAVER_REDIRECT_URI }}" >> $GITHUB_ENV
          echo "NAVER_USER_INFO_URI=${{ secrets.NAVER_USER_INFO_URI }}" >> $GITHUB_ENV

      - name: Grant execute permission for Gradle
        run: chmod +x ./gradlew

      - name: Apply Spotless Format
        run: ./gradlew spotlessApply

      - name: Commit and Push if Needed
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .
          git commit -m "chore: apply spotless formatting" || echo "No changes"
          git push origin HEAD:${{ github.ref_name }}

      - name: Check Google Style Format
        run: ./gradlew spotlessCheck

      - name: Build & Run Tests
        run: ./gradlew test

      - name: Build Application
        run: ./gradlew clean build
